name: openapi

# Controls when the workflow will run
on:
  # triggered on a custom event
  repository_dispatch:
    types: [trigger_ci]
 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      sdk:
        description: 'Fetch latest openapi spec'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  setup:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup node
        uses: actions/setup-node@v3

      - name: Download json
        run: npm install json

      - name: Download Fern
        run: npm install -g fern-api

      # Runs a single command using the runners shell
      - name: Download swagger, generate postman and push it
        id: push-openapi
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
        run: |
          echo "$GITHUB_WORKSPACE"
          wget https://api.tryvital.io/openapi.json -O- | npx json > ./fern/openapi/openapi.json
          fern generate --group postman --log-level debug
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add ./fern/openapi/openapi.json
          git add ./postman/collection.json
          git commit -m "[automated commit] update openapi.json and collection.json"
          git push
          echo "release_commit=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"
