name: openapi.json line count

on:
  [pull_request]

jobs:
  check-line-count:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: openapi.json line count
        run: |
          file="fern/openapi/openapi.json"
          echo "Checking $file"
          line_count=$(wc -l < "$file")

          if [ "$line_count" -lt 2 ]; then
            echo "$file has not been formatted to a multiline JSON file."
            exit 1
          fi
