name: openapi.json line count

on:
  pull_request:
    paths:
      - fern/openapi/openapi.json

jobs:
  check-line-count:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: fern

    steps:
      - name: openapi.json line count
        run: |
          echo $(ls)
          file="openapi/openapi.json"
          line_count=$(wc -l < "$file")

          if [ "$line_count" -lt 2 ]; then
            echo "$file has not been formatted to a multiline JSON file."
            exit 1
          fi
