name: Check openapi.json Line Count

on:
  pull_request:
    paths:
      - fern/openapi/openapi.json

jobs:
  check-line-count:
    runs-on: ubuntu-latest

    steps:
      - name: Check openapi.json Line Count
        run: |
          echo $(pwd)
          echo $(ls)
          file="fern/openapi/openapi.json"
          line_count=$(wc -l < "$file")

          if [ "$line_count" -lt 2 ]; then
            echo "$file has not been formatted to a multiline JSON file."
            exit 1
          fi
